### ISSUE TITLE
Change fixed IP addresses to enable user-specified addresses

### ISSUE THREAD

**Issue by Lyonlancer5** [Mylogyc/ModNet#1]
## Overview

As of release b1.0.2, the server and client are fixed in the address `lyonetworks.dyndns.org:30491`. This, although meant for testing, is **_NOT**_ meant for production use. This is a major issue and should be fixed ASAP.

There are various methods which we could use to enable user-specified addresses, namely:
- Use a file (e.g. server.properties, like in Minecraft servers) to not only allow custom addresses, but to also configure the server/client _during_ runtime.
- Enable the use of the arguments passed in `main(String[] args)` to allow customization _before_ runtime.
## Affected releases
- ModNetServer - b1.0.2
- ModNetClient - b1.0.2
- ModNetHostClient - b1.0.2

**Comment by Leidi-Kana** [comment]
Finished fix as of April 21, 2016 - will be pushing to a dev branch once preparations are complete (alongside release b2.0) and also uploading the release by next week

Configuration files are in the name of "settings.properties" and can be found in the folder where the jar files are run.

**Comment by Leidi-Kana** [comment]
-- closing, this repository will be archived and deleted within 90 days of this notice.

Superseded by Project Curiosa.
