### ISSUE TITLE
File transfer re-implementation

### ISSUE THREAD

**Issue by Lyonlancer5** [Mylogyc/ModNet#2]
## Overview

The current implementation of both the `download` and `upload` commands get the raw data of the file being interacted with. This implementation is _unstable_ on bad network connections and could lead to corrupt files on both sides.

Although there is already a fixed 2GB (32-bit integers...)  limit per file on upload and download, it would be better to implement a sort of data compression to reduce file size on transfer and decompress on receive.
## Affected releases:
- ModNetClient - b1.0.2
- ModNetHostClient - b1.0.2

**Comment by Leidi-Kana** [comment]
This issue should also need to fix an `OutOfMemoryError` due to the default allocation of a VM. As the file is read through memory, it would be very unwise to use this in very large files. This issue should cover a re-implementation of the entire `download` and `upload` commands.

**Comment by Leidi-Kana** [comment]
A way to effectively transfer large files is to split the file into manageable chunks of byte arrays, which, although would need to have another additional `Command` added to the `MessageObject`, would use less RAM and also less network-intensive.

There is a need to set a maximum size of a chunk size (length of the byte array) to prevent, again, the issue regarding an `OutOfMemoryError` being thrown. We could let the user configure the limit or implement dynamic file splitting (chunk size changes depending on the file size) to also overcome the 2GB limitation of byte arrays. The ideal limit of a chunk size to send would be around 10MB, so as to send information to the server the quickest way possible, or 2MB, which would allow the server to allocate more memory to other users.

Either way, we'll see how this issue will develop.

**Comment by Lyonlancer5** [comment]
>  The ideal limit of a chunk size to send would be around 10MB, so as to send information to the server the quickest way possible, or 2MB, which would allow the server to allocate more memory to other users.

Limited to 64KB packets by default

**Comment by Leidi-Kana** [comment]
-- closing, this repository will be archived and deleted within 90 days of this notice.

Superseded by Project Curiosa.
