### ISSUE TITLE
Notify online clients of new connections

### ISSUE THREAD

**Issue by Lyonlancer5** [Mylogyc/ModNet#3]
## Overview

The current implementation of the server does **_NOT**_ notify existing connected clients of any newly connected clients. This could be fixed by sending a packet notifying all connected users of a newly connected client.

Such as this:

```
//hook on code ModNetServer.ClientThread
ClientThread(Socket socket){
    . . .
    display(username + " just connected from " + socket.getInetAddress());
    //send a packet containing username
    writeMsg(new MessageObject(username, "_server", "connected"))
    . . .
}
```

Client side should also know how to interpret this message.
## Affected releases
- ModNetClient b1.0.2
- ModNetHostClient b1.0.2
- ModNetServer b1.0.2

**Comment by Leidi-Kana** [comment]
Finished fix as of April 21, 2016 - will be pushing to a dev branch once preparations are complete (alongside release b2.0) and also uploading the release by next week

As the messaging system has also changed, the fix should have been already applied in b2.0

**Comment by Leidi-Kana** [comment]
-- closing, this repository will be archived and deleted within 90 days of this notice.

Superseded by Project Curiosa.
