### ISSUE TITLE
GUI implementation

### ISSUE THREAD

**Issue by Lyonlancer5** [Mylogyc/ModNet#4]
## Overview

A graphical user interface would be a nice touch to ModNet (only applies to the Host Client and the Server).

Generally, the UI would consist of a list box containing all online users, a text area containing all the events logged and a text box for typing in commands.

**Comment by Leidi-Kana** [comment]
Currently low-priority at the moment. Re-open this issue once b2.0 has been released.

**Comment by Lyonlancer5** [comment]
OK, so I managed to create a GUI, but its for the server. Client-side GUIs would soon be implemented, and also the server GUI would need to be reworked after b2.0 release.

Dev commit would be up soon.

**Comment by Leidi-Kana** [comment]
-- closing, this repository will be archived and deleted within 90 days of this notice.

Superseded by Project Curiosa.
