### ISSUE TITLE
Network implementation -> UDP

### ISSUE THREAD

**Issue by Lyonlancer5** [Mylogyc/ModNet#7]
### Overview

The current implementation of TCP connection is a bit of an off-shot compared to UDP, as the objective is to send "packets of data" through the network. By establishing a direct connection to a remote host or server, it slows down the network because the sender must receive a response indicating whether the receiver did receive the data.

Meanwhile, in UDP, the sender only sends data, and will only know if the receiver receives the packet if the target sends a reply. There is also not a need for a direct remote connection.
### Target

By the implementation of 2.0+, all servers and clients must implement a UDP-styled networking scheme to reduce network load
#2 is actually related to this. By sending data in packets instead of "the whole thing," the server can then answer to multiple requests given by different clients.

**Comment by Lyonlancer5** [comment]
Referring to the "Byzantine General's Problem"

>Meanwhile, in UDP, the sender only **sends** data, and will only [be notified] if the target sends a reply.

Setting a timeout value to a reply may help alleviate the problem. It took a lot of accidents and books to research about the possible problems and solutions.

**Comment by Leidi-Kana** [comment]
-- closing, this repository will be archived and deleted within 90 days of this notice.

Superseded by Project Curiosa.
Also no longer needed to implement a server due to using of an existing network infrastructure.
